services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nzo\LeftSidebarBundle\Menu\MenuLeftSidebar:
        arguments:
            $leftSidebarData: '%nzo_left_sidebar.menu%'
            $appEnvironment: '%env(APP_ENV)%'

    Nzo\LeftSidebarBundle\Twig\LeftSidebarExtension:
        tags:
            - { name: twig.extension }
