language: php

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email:
    - alakhefifi@gmail.com
